debug = false

logLevel = "debug"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
swarmMode = false
endpoint = "unix:///var/run/docker.sock"
domain = "mon.anvibo.com"
watch = true

[api]
dashboard = true

[forwardingTimeouts]
dialTimeout = "30s"

[acme]
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
email = "ssl@anvibo.com"
acmeLogging = true

[acme.httpChallenge]
entryPoint = "http"
